# Generated by Django 3.0.5 on 2020-04-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(verbose_name='Date And Time')),
                ('Basic', models.BooleanField(blank=True, verbose_name='Basic Checkup')),
                ('Electrical', models.BooleanField(blank=True, verbose_name='Electrical Checkup')),
                ('Mechanical', models.BooleanField(blank=True, verbose_name='Mechanical Checkup')),
                ('Installation', models.BooleanField(blank=True, verbose_name='Installation work')),
                ('Water', models.BooleanField(blank=True, verbose_name='Chilled Water System')),
                ('BasicNotes', models.CharField(blank=True, max_length=100, verbose_name='Basic Checkup Notes')),
                ('ElectricalNotes', models.CharField(blank=True, max_length=100, verbose_name='Electrical Checkup Notes')),
                ('MechanicalNotes', models.CharField(blank=True, max_length=100, verbose_name='Mechanical Checkup Notes')),
                ('InstallationNotes', models.CharField(blank=True, max_length=100, verbose_name='Installation work Notes')),
                ('WaterNotes', models.CharField(blank=True, max_length=100, verbose_name='Chilled Water System Notes')),
                ('Customer', models.CharField(max_length=20, verbose_name="Customer's Name")),
            ],
        ),
    ]
