# Generated by Django 3.0.5 on 2020-04-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date And Time'),
        ),
    ]
