# Generated by Django 3.0.5 on 2020-04-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20200426_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Basic',
            field=models.CharField(max_length=4, verbose_name='Basic Checkup'),
        ),
        migrations.AlterField(
            model_name='data',
            name='Date',
            field=models.CharField(max_length=20, verbose_name='Date And Time'),
        ),
        migrations.AlterField(
            model_name='data',
            name='Electrical',
            field=models.CharField(max_length=4, verbose_name='Electrical Checkup'),
        ),
    ]
