# Generated by Django 3.0.5 on 2020-04-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20200427_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Basic',
            field=models.BooleanField(blank=True, verbose_name='Basic Checkup'),
        ),
        migrations.AlterField(
            model_name='data',
            name='Date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date And Time'),
        ),
        migrations.AlterField(
            model_name='data',
            name='Electrical',
            field=models.BooleanField(blank=True, verbose_name='Electrical Checkup'),
        ),
    ]
