# Generated by Django 3.0.5 on 2020-04-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20200427_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Basic',
            field=models.CharField(max_length=8, verbose_name='Basic Checkup'),
        ),
        migrations.AlterField(
            model_name='data',
            name='Date',
            field=models.CharField(max_length=30, verbose_name='Date And Time'),
        ),
        migrations.AlterField(
            model_name='data',
            name='Electrical',
            field=models.CharField(max_length=8, verbose_name='Electrical Checkup'),
        ),
        migrations.AlterField(
            model_name='data',
            name='Installation',
            field=models.CharField(max_length=8, verbose_name='Installation work'),
        ),
        migrations.AlterField(
            model_name='data',
            name='Mechanical',
            field=models.CharField(max_length=8, verbose_name='Mechanical Checkup'),
        ),
        migrations.AlterField(
            model_name='data',
            name='Water',
            field=models.CharField(max_length=8, verbose_name='Chilled Water System'),
        ),
    ]
