# Generated by Django 3.0.5 on 2020-04-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_auto_20200427_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Date',
            field=models.DateTimeField(verbose_name='Date And Time'),
        ),
    ]
